// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJnO3F2mtfVEuocaZDYtllJXvj3Gjt9v8',
    appId: '1:980291827167:web:d94c0447869dc4cdf7806a',
    messagingSenderId: '980291827167',
    projectId: 'intec-pro',
    authDomain: 'intec-pro.firebaseapp.com',
    databaseURL: 'https://intec-pro-default-rtdb.firebaseio.com',
    storageBucket: 'intec-pro.appspot.com',
    measurementId: 'G-P1ZK08YQTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY1WoUNyUxURYOO_IUgGoMa6aKVT1uWvY',
    appId: '1:980291827167:android:ca5e3c52fc2e8651f7806a',
    messagingSenderId: '980291827167',
    projectId: 'intec-pro',
    databaseURL: 'https://intec-pro-default-rtdb.firebaseio.com',
    storageBucket: 'intec-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxi2rUoTQ3wnUahgA7GUaFr18dyFkNCTY',
    appId: '1:980291827167:ios:4e6b03243dba2188f7806a',
    messagingSenderId: '980291827167',
    projectId: 'intec-pro',
    databaseURL: 'https://intec-pro-default-rtdb.firebaseio.com',
    storageBucket: 'intec-pro.appspot.com',
    iosClientId: '980291827167-tsm6ef6hah51ofq8fsca698p615297kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.intechpro',
  );
}
